
lang = {'en': {
    1: 'Connected to FTP',
    2: 'Error connect to FTP',
    43: 'Changed directory to Dist',
    3: 'Changed directory to ',
    4: 'Error change directory to ',
    5: 'Downloading app files...',
    6: 'Zip app downloaded',
    7: 'Error downloading app',
    8: 'Changing directory to Data',
    9: 'Downloading Data file...',
    10: 'Zip Data downloaded',
    11: 'Error downloading Data',
    12: 'Disconnecting from FTP...',
    13: 'Disconnected from FTP',
    14: 'Error disconnect from ftp',
    15: 'Checking for existing app folders',
    16: 'App directory exists',
    17: 'App directory not exists',
    18: 'Config directory exists',
    19: 'Config directory not exists',
    20: 'Data directory exists',
    21: 'Data directory not exists',
    22: 'Removing old version',
    23: 'Old version removed',
    24: 'Error removing old version',
    25: 'killing Windows task',
    26: 'Windows task killed',
    27: 'Error killing Windows task',
    28: 'Removing Config and Data!',
    44: 'Config and Data removed',
    29: 'Error removing Config and Data',
    30: 'Creating new app folder',
    31: 'New app folder created as ',
    32: 'Error create new app folder',
    33: 'Creating new config folder',
    34: 'New config folder created as ',
    35: 'Error create new config folder',
    36: 'Creating new data folder',
    37: 'New Data folder created as ',
    38: 'Error create new Data folder',
    39: 'Extracting files from ',
    40: 'Extracted files from ',
    41: 'Error extracting files from ',
    42: 'Error removing zip ',
    45: 'Removing zip ',
    46: 'Removed zip',
    47: 'Creating Windows shortcut',
    48: 'Windows shortcut created',
    49: 'Error creating Windows shortcut',
    50: 'Removing Windows shortcut',
    51: 'Error removing Windows shortcut',
    52: 'Windows shortcut removed',
    53: '\nTo reinstall or upgrade ONLY THE APP press 1\nTo reinstall or upgrade THE APP and THE DATA\n(WARNING: ACTUAL DATA WILL BE LOST!) press 2\nTo uninstall ALL press 3\nTo backup THE DATA press 4\nCancel and EXIT press 5\n',
    54: '\nTo reinstall or upgrade THE APP press 2\nTo uninstall ALL press 3\nTo backup THE DATA press 4\nCancel and EXIT press 5\n',
    55: '\nTo install THE APP press 1\nTo reinstall or upgrade THE APP and THE DATA\n(WARNING: ACTUAL DATA WILL BE LOST!) press 2\nTo uninstall ALL press 3\nTo backup THE DATA press 4\nCancel and EXIT press 5\n',
    56: '\nTo install THE APP press 2\nCancel and EXIT press 5\n',
    60: 'Programm already instaled, you can reinstall',
    61: 'Programm not yet instaled, please install',
    62: 'Data not installed, please reinstall the programm',
    63: 'Only data installed, please install the programm',
    64: 'Installing...',
    65: 'Successfully installed',
    66: 'Unistalling...',
    67: 'Successfully uninstalled',
    68: 'Error occured, please reinstall',
    69: '',
    70: '',
    71: '',
}}

buttons = {'en': {
    1: 'Ok',
    2: 'Cancel',
    3: 'No',
    4: 'Install',
    5: 'Uninstall',
    6: 'Installation',
    7: 'Welcome to',
    8: 'installer',
    9: 'Reinstall',
    10: 'Exit'
}}
